// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddGreetingHandler(ReducerEventContext ctx, string text);
        public event AddGreetingHandler? OnAddGreeting;

        public void AddGreeting(string text)
        {
            conn.InternalCallReducer(new Reducer.AddGreeting(text));
        }

        public bool InvokeAddGreeting(ReducerEventContext ctx, Reducer.AddGreeting args)
        {
            if (OnAddGreeting == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAddGreeting(
                ctx,
                args.Text
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddGreeting : Reducer, IReducerArgs
        {
            [DataMember(Name = "text")]
            public string Text;

            public AddGreeting(string Text)
            {
                this.Text = Text;
            }

            public AddGreeting()
            {
                this.Text = "";
            }

            string IReducerArgs.ReducerName => "add_greeting";
        }
    }
}
