// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class GreetingHandle : RemoteTableHandle<EventContext, Greeting>
        {
            public override string RemoteTableName => "greeting";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Greeting row) => row.Id;

                public IdUniqueIndex(GreetingHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal GreetingHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(Greeting row) => row.Id;
        }

        public readonly GreetingHandle Greeting;
    }

    public sealed class GreetingCols
    {
        public global::SpacetimeDB.Col<Greeting, uint> Id { get; }
        public global::SpacetimeDB.Col<Greeting, string> Text { get; }

        public GreetingCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Greeting, uint>(tableName, "id");
            Text = new global::SpacetimeDB.Col<Greeting, string>(tableName, "text");
        }
    }

    public sealed class GreetingIxCols
    {
        public global::SpacetimeDB.IxCol<Greeting, uint> Id { get; }

        public GreetingIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Greeting, uint>(tableName, "id");
        }
    }
}
